### ISSUE TITLE
Is psaw down?

### ISSUE THREAD

**Issue by YS-SHI-93** [dmarx/psaw#106]
Hi Loyal user here.

I tried several times today but it seems psaw is not working properly today.
 
with these code
```
from psaw import PushshiftAPI
api = PushshiftAPI()
```

A exception was throw out:

C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\psaw\PushshiftAPI.py:192: UserWarning: Got non 200 code 404
  warnings.warn("Got non 200 code %s" % response.status_code)

C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\psaw\PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.

  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")

....

Exception: Unable to connect to pushshift.io. Max retries exceeded.

**Comment by r92546024** [comment]
i have same issue...

**Comment by dmarx** [comment]
psaw is just a wrapper library, the actual API (pushshift.io) is independent and hosted by someone else. try asking on https://www.reddit.com/r/pushshift 

also, i hvaen't been maintaining this repo for some time. you should consider migrating to https://github.com/mattpodolak/pmaw
