### ISSUE TITLE
Ratelimit increase

### ISSUE THREAD

**Issue by pushshift** [dmarx/psaw#11]
I have increased the rate limit to 200 requests per minute.  The current rate limit can be found by querying https://api.pushshift.io/meta

The key "server_ratelimit_per_minute" holds the global rate limit for the API.

I would suggest that you query that endpoint and get the value when setting the rate limit (perhaps when instantiating the class).  That way, if the limit ever changes, it will automatically be updated without you having to change that value manually.

Thanks!

**Comment by dmarx** [comment]
Added in commit aee59d1
