### ISSUE TITLE
Getting Count from Aggregation

### ISSUE THREAD

**Issue by dhkatz** [dmarx/psaw#12]
If I were to directly query the api like so:

https://api.pushshift.io/reddit/search/comment/?author=MCiLuZiionz&subreddit=Paragon&aggs=subreddit&size=0

```json
{
    "aggs": {
        "subreddit": [
            {
                "doc_count": 1512,
                "key": "paragon"
            }
        ]
    },
    "data": []
}
```
I can quickly get the resultant counts from my aggregation if I were to say `json['aggs']['subreddit']['doc_count']`. 

I don't see any way to get this using PSAW other than doing `len(list(api.search_comments(subreddit='Paragon', author='MCiLuZiioNz', aggs='subreddit', size=0))`.

This is very slow because the list has to be generated using the generator returned from search_comments() before I can measure the length.

**Comment by dmarx** [comment]
Just pushed a new version to pypi with aggs support that should satisfy your needs. If an aggs parameter is provided, the first result returned by the generator will be the aggs result, so now you can do this:

```
gen = api.search_comments(subreddit='Paragon', author='MCiLuZiioNz', aggs='subreddit', sort='asc')
next(gen) # {'subreddit': [{'doc_count': 1514, 'key': 'paragon'}]}
len(list(gen)) # 1514
```
