### ISSUE TITLE
Appending created_utc at every request

### ISSUE THREAD

**Issue by 1649** [dmarx/psaw#16]
Hey!

After troubleshooting with u/stuck_in_the_matrix it became clear that when requesting a large amount of comments from a subreddit the GET request limit was reached. The following request was done at the side of the API when appending all of the results in a list.

{"time":1525859105547,"client":"myip","method":"GET","request":"GET /reddit/comment/search/?subreddit=Ethereum&limit=500&before=1472703782&sort=desc&filter=body&filter=id&filter=author&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc&filter=created_utc.....

Probably this is caused by the created_utc which is appended every time:

![screen shot 2018-05-09 at 13 03 58](https://user-images.githubusercontent.com/27900824/39816229-f374d90e-539a-11e8-9606-0bc3c1f7b5bd.png)

**Comment by dmarx** [comment]
Yikes! I'll prioritize this. Thanks!
