### ISSUE TITLE
error using search_submissions() when providing praw.Reddit()

### ISSUE THREAD

**Issue by robhawkins** [dmarx/psaw#22]
I'm getting an error when providing a `praw.Reddit()` instance to `search_submissions()`.  `search_comments()` seems to work fine.

Here is the code and error,

```
import praw
from psaw import PushshiftAPI
import time
from pprint import pprint


r = praw.Reddit(...)
api = PushshiftAPI(r)

gen = api.search_submissions()
list(gen)

```
...

```
Traceback (most recent call last):
  File "findPopularNewSubmissions.py", line 26, in <module>
    lgen=list(gen)
  File "/home/rob/anaconda3/lib/python3.6/site-packages/psaw/PushshiftAPI.py", line 234, in _praw_search
    prefix = self._thing_prefix[kwargs['kind'].title()]
KeyError: 'Submission'

```

**Comment by NotCompsky** [comment]
Solution:

Under class PushshiftAPIMinimal, set \_thing_prefix['Submission']='t3_'

Currently it has \_thing_prefix['Link']='t3_', which I assume is from an older version of PRAW.

**Comment by robhawkins** [comment]
Sweet, thanks @NotCompsky ! I made a PR #24 for this.
