### ISSUE TITLE
Bug in _praw_search when fetching comment ids

### ISSUE THREAD

**Issue by skypher** [dmarx/psaw#30]
When calling `search_comments(submission_id=sub.id)` and the submission has no comments, a bug in `_praw_search` is triggered.

Quick fix:
```python
        for batch in gen:
+           if batch == []:
+              return
            if using_gsci:
                fullnames = [prefix + base36id for base36id in batch]
```

Excuse my brevity and the fact that I just submitted a quick band-aid. I don't have much time right now after debugging this issue and I hope my bug report will help. Let me know if you need more info. Thanks for psaw, friend.

**Comment by dmarx** [comment]
Nope, that was plenty descriptive. just pushed a new release which includes a fix for this bug. Thanks!
