### ISSUE TITLE
Converting output to EXEL/readable data

### ISSUE THREAD

**Issue by ghost** [dmarx/psaw#32]
What format does PSAW output? E.G. how to convert to an EXEL doc?

**Comment by dmarx** [comment]
psaw outputs objects that are basically named tupples. one of the attributes on this object is `d_`, which is a dict that contains all of the key-value pairs for attributes of the content you downloaded. A simple solution for dumping this into excel is to use these dicts to instantiate a pandas DataFrame, which then has `to_csv` and `to_excel` methods you can use to dump the data you downloaded. Demo:

```
from psaw import PushshiftAPI
import pandas as pd

api = PushshiftAPI()
gen = api.search_comments(author='someuser')
df = pd.DataFrame([c.d_ for c in gen])
df.to_csv('/path/to/output/data.csv')
```

Now that you mention it, maybe I'll add a CLI to facilitate downloading and dumping data for less technical users. Thanks for the idea!
