### ISSUE TITLE
Simple CLI

### ISSUE THREAD

**Issue by dmarx** [dmarx/psaw#33]
Facilitate downloading from pushshift for non-technical users. E.g. reduce downloading a user's activity history to something like:

```
psaw --comments --author userName --outpath /path/to/file/data.csv
```

**Comment by dmarx** [comment]
youtube-dl has a good model to emulate.

* Dedicted class for handling argument parsing
* __main__.py handles `if __name__ == '__main__'` block, imports from main namespace
* Dedicated function for orchestrating CLI behavior

**Comment by arlenk** [comment]
Created a pull request of a potential cli wrapper here https://github.com/dmarx/psaw/pull/34

Supports filtering by authors, subreddits, and query string (have not added before or after yet, but will add those as well).

Let me know if this is along the lines you were thinking.

**Comment by dmarx** [comment]
Just wanted to let you know this is on my radar. I was out of town for several weeks and I just started a new job so I've been busy, but I'll try to take a look at this PR soon.

**Comment by arlenk** [comment]
> Just wanted to let you know this is on my radar. I was out of town for several weeks and I just started a new job so I've been busy, but I'll try to take a look at this PR soon.

ok, no problem.  In the meantime, I added support for before and after.  You can pass in anything that dateutil.parser supports (ie, 20180101) or specials values like 30d for 30 days that the pusshift api supports.

Alternatively, it would be easy to add support for a better datetime parser (such as https://dateparser.readthedocs.io/en/latest/) if you are ok with an additional dependency.  This way we can ignore special casing for values like 30d and instead convert everything to a python dateitme and then to an epoch value for the pushshift api.  I think that would be cleaner and more flexible at the cost of one more dependency though.

**Comment by pushshift** [comment]
Hey there! Currently you can pass datetimes for before and after like this: "2018-12-05 14:33:00" What I think would be more appropriate is to follow ISO-8601 and make the format like this: 

2018-12-05T11:33:56+00:00
2018-12-05T11:33:56Z

This would allow for providing time zone offsets as well. I wanted to get some thoughts on this since it relates to this issue. Do you think this would be most appropriate? The parameters will also continue to support epoch timestamps and convenience values (m,h,d for minutes,hours,days)

**Comment by arlenk** [comment]
> Do you think this would be most appropriate? The parameters will also continue to support epoch timestamps and convenience values (m,h,d for minutes,hours,days)

Hi, I think that sounds like a great idea.  It's easy enough on our end to pass whatever format the API expects, so choosing an existing standard sounds good,
