### ISSUE TITLE
Scraping how many submissions

### ISSUE THREAD

**Issue by Zachary24** [dmarx/psaw#39]
Is there any way to (fastly) scrape how many submissions a subreddit has? Or at least an estimate? Im currently building a script that scrapes the urls, removes each url that doesn't contain an extension such as .jpg or .mp4, adds those to the download.csv as well as the history.csv, then passes that csv to wget. When scraping a large subreddit it just sits there, and I have no way of telling about how far along it is, therefore doing a small/simple scrape beforehand would allow me to check how many lines are in the scrape.csv and compare it to the rough amount of submissions every couple of seconds. I hope what i said makes sense! Thanks!

**Comment by pushshift** [comment]
**Get number of submissions per month for a subreddit:**

https://api.pushshift.io/reddit/submission/search/?aggs=created_utc&frequency=month&subreddit=askreddit

**Get number of submissions per day for a subreddit for past year:**

https://api.pushshift.io/reddit/submission/search/?aggs=created_utc&frequency=day&after=365d&subreddit=askreddit

Is this what you're looking for?

**Comment by dmarx** [comment]
Check the documentation on the "aggs" parameter. Here's an example of querying how many submissions a subreddit has, grouped by year. You can just sum over the results to get the total count of submission.

```
from psaw import PushshiftAPI

api = PushshiftAPI()
gen = api.search_comments(subreddit='programming', 
                          aggs='created_utc',
                          frequency='year'
                         )
next(gen)
```

Which returns:

```
{'created_utc': [{'doc_count': 37611, 'key': 1136073600},
  {'doc_count': 217815, 'key': 1167609600},
  {'doc_count': 449840, 'key': 1199145600},
  {'doc_count': 717131, 'key': 1230768000},
  {'doc_count': 674953, 'key': 1262304000},
  {'doc_count': 458638, 'key': 1293840000},
  {'doc_count': 360585, 'key': 1325376000},
  {'doc_count': 382681, 'key': 1356998400},
  {'doc_count': 448255, 'key': 1388534400},
  {'doc_count': 510005, 'key': 1420070400},
  {'doc_count': 506656, 'key': 1451606400},
  {'doc_count': 500817, 'key': 1483228800},
  {'doc_count': 486496, 'key': 1514764800}]}
```

"key" here is a unix date corresponding to a year, and "doc_count" is the number of submissions that year.

**Comment by monk1337** [comment]
It's not working. Could you please check and update how to scrape how many submissions a subreddit has till now?
