### ISSUE TITLE
get top posts from a particular day

### ISSUE THREAD

**Issue by gitlerat** [dmarx/psaw#41]
Hi, lets say I want to get the top 10 most upvoted posts from a particular day, from a particular subreddit. Is there a way to do this with psaw?
kind greetings :)

**Comment by pushshift** [comment]
Getting the top 10 most upvoted posts from a particular day is currently not possible but it's a feature that will be added soon for Pushshift. Presently, you can only rank posts by the number of comments (this metric is updated).

PRAW might be able to hit the top link for a subreddit and limit to 24 hours -- that may be another possibility.

**Comment by gitlerat** [comment]
Hi @pushshift 
thank you for your response :) is there some status progress on your update because you wrote back in september 2018 that the update is "coming soon".

Thanks for the afford!
