### ISSUE TITLE
KeyError upvote_ratio

### ISSUE THREAD

**Issue by JonathanBouligny** [dmarx/psaw#43]
```
    to_dict = vars(posts[i])
    sub_dict = {field:str(to_dict[field]) for field in fields}
    # sub_dict["author"] = str(sub_dict["author"])
    print(sub_dict)
    list_of_items.append(sub_dict)
```

Hi, I think the submission object is doing lazy loading of upvote ratio and I would like to convert it to a dict using the code i posted here and output upvote ratio with it. How can i do this without printing which forces the rest of the data to load?

Thank you!

**Comment by dmarx** [comment]
If you're instantiating your `api` instance with a praw object, you should ask the praw folks since it's their Submission object you're working with. Otherwise, if you're using vanilla psaw, check out the `.d_` attribute.
