### ISSUE TITLE
Add beta API support

### ISSUE THREAD

**Issue by dmarx** [dmarx/psaw#6]
https://www.reddit.com/r/pushshift/comments/8cdbiw/new_version_of_pushshift_api_is_entering_beta_for/

Simplest solution is probably to just move base_url from being a class attribute to an __init__argument that defaults to the api subdomain. In the "user friendly" PushshiftAPI class, I could add a simpler "use_beta" parameter to the __init__ that picks which url to use for the base_url argument.

**Comment by dmarx** [comment]
beta API seems to be down. Added support in (local) beta_api branch, waiting for opportunity to test.

**Comment by pushshift** [comment]
Beta API should be back up.  I recently upgraded the OS to Ubuntu 18.04 and did some other upgrades.  It's currently loading submissions and comments for 2017 but there should be enough data available within the API to start writing code against. 

Please let me know if you find any issues or have suggestions for making the API better.  I appreciate your help!

**Comment by dmarx** [comment]
see domain parameter in https://github.com/dmarx/psaw/commit/1b10c11801c3a298cf50d3ed6f44598c9497b0cd, currently on dev branch

**Comment by dmarx** [comment]
published in v0.0.3
