### ISSUE TITLE
Missing parentheses causes uncaught exception on connection error

### ISSUE THREAD

**Issue by cmicek1** [dmarx/psaw#73]
There should be an extra set of parentheses around `i+1` on line 188 of `PushshiftAPI.py`:
`log.debug("Connection error caught, retrying. Connection attempts so far: %s" % (i+1))`
instead of
`log.debug("Connection error caught, retrying. Connection attempts so far: %s" % i+1)`.

Otherwise Python thinks you're concatenating a string and an int, and gets mad.

**Comment by jfa501** [comment]
I have also come across this issue and agree that an extra set of parentheses would solve this.
