### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by julianl28** [dmarx/psaw#8]
(Sorry if I'm doing this wrong - first time submitting a bug report on github)

I've tried this on two different linux machines and get the same error. I've tried Python 3.4.2 and 3.5.3. Both have the same version (v0.0.1) of PSAW installed.

If I run the following example code from the documentation:

```
from psaw import PushshiftAPI

api = PushshiftAPI()

# The `search_comments` and `search_submissions` methods return generator objects
gen = api.search_submissions(limit=100)
results = list(gen)
```

I get the following error:

```
Traceback (most recent call last):
  File "./mostrecent.py", line 9, in <module>
    results = list(gen)
  File "/usr/local/lib/python3.4/dist-packages/psaw/PushshiftAPI.py", line 108, in _query
    thing = self._wrap_thing(thing, kind)
  File "/usr/local/lib/python3.4/dist-packages/psaw/PushshiftAPI.py", line 45, in _wrap_thing
    thing['created'] = self._epoch_utc_to_local(thing['created_utc'])
  File "/usr/local/lib/python3.4/dist-packages/psaw/PushshiftAPI.py", line 41, in _epoch_utc_to_local
    return epoch - self.utc_offset_secs
  File "/usr/local/lib/python3.4/dist-packages/psaw/PushshiftAPI.py", line 33, in utc_offset_secs
    self._utc_offset_secs =  dt.utcnow().astimezone().utcoffset().total_seconds()
ValueError: astimezone() cannot be applied to a naive datetime
```

One system has its timezone set to UTC and the other set to GMT. Could it be a timezone issue?

**Comment by dmarx** [comment]
Interesting. Doesn't look like you're doing anything wrong. I think the simplest solution would be to wrap the code that sets self._utc_offset_secs in a try/except block that sets that the value to 0 if this exception pops up. Wanna submit a PR?

**Comment by julianl28** [comment]
Do you know the TZ used by reddit? I may be over simplifying, but wouldn't it be easier to set the time zone using something like this (example code I found):

    start_date = start_date.replace(tzinfo=local_tz)

I'm new to this, so happy to go with your recommendation.

**Comment by dmarx** [comment]
The intention of that attribute is to set the timezone local to the user's
configuration. If you used praw as a logged in user, it returns results in
utc and the user's configured timezone. This later attribute is what this
feature is intended to simulate.

**Comment by dmarx** [comment]
@julianl28 Can you help me test a fix? Reinstall psaw with the following command and let me know if you still have issues or not:

    pip install --upgrade -e git+git://github.com/dmarx/psaw.git@utc_fix

If it works, let me know so I can merge the change to master and close the issue.

Thanks!

**Comment by julianl28** [comment]
That works like a charm, thank you. :)

**Comment by 1649** [comment]
Hey,

I have tried installing the PSAW package again as well as manually adding the try/except block in the PushshiftAPI code. However, I still get the ValueError: astimezone() cannot be applied to a naive datetime. 

Any ideas?

**Comment by dmarx** [comment]
Did you follow the reinstallation instructions above? I haven't deployed a new release to pypi with this fix yet.

**Comment by 1649** [comment]
Yes I tried but got this in my terminal: Could not detect requirement name for 'git+git://github.com/dmarx/psaw.git@utc_fix', please specify one with #egg=your_package_name

Therefore I tried it manually

**Comment by dmarx** [comment]
Post the code you tried in a gist. If you copieded the new try/except block, it shouldn't be possible for a ValueError to get thrown there. You're probably still using the class loaded from the installed package rather than your manual fix. That's my guess, anyway.

**Comment by dmarx** [comment]
Also post your full error message and system specs, please.

**Comment by 1649** [comment]
https://gist.github.com/1649/0f422011d3719426ea16d8d1ae9b9dbf

Thanks a lot for your time!

**Comment by julianl28** [comment]
I had a similar error from pip. Try running the command without the '-e' part.

**Comment by 1649** [comment]
I received a xcron error: xcrun error when running without the '-e' part: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

However, after installing the xcode developers tools by `xcode-select --install` I could run the `pip install --upgrade git+git://github.com/dmarx/psaw.git@utc_fix`

Unfortunately after updating the time ValueError still occurs.
